<a href="https://colab.research.google.com/github/tunnu-sahni/Codsoft/blob/main/csv_read1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd

In [ ]:
df = pd.read_csv("/content/sample_data/california_housing_train.csv")
df

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value
0,-114.31,34.19,15.0,5612.0,1283.0,1015.0,472.0,1.4936,66900.0
1,-114.47,34.40,19.0,7650.0,1901.0,1129.0,463.0,1.8200,80100.0
2,-114.56,33.69,17.0,720.0,174.0,333.0,117.0,1.6509,85700.0
3,-114.57,33.64,14.0,1501.0,337.0,515.0,226.0,3.1917,73400.0
4,-114.57,33.57,20.0,1454.0,326.0,624.0,262.0,1.9250,65500.0
...,...,...,...,...,...,...,...,...,...
16995,-124.26,40.58,52.0,2217.0,394.0,907.0,369.0,2.3571,111400.0
16996,-124.27,40.69,36.0,2349.0,528.0,1194.0,465.0,2.5179,79000.0
16997,-124.30,41.84,17.0,2677.0,531.0,1244.0,456.0,3.0313,103600.0
16998,-124.30,41.80,19.0,2672.0,552.0,1298.0,478.0,1.9797,85800.0
16999,-124.35,40.54,52.0,1820.0,300.0,806.0,270.0,3.0147,94600.0

[link text](https://)** opening a csv file**

In [ ]:
import pandas as pd
pd.read_csv("/content/sample_data/mnist_test.csv", sep=",")

,7,0,0.1,0.2,0.3,0.4,0.5,0.6,0.7,0.8,...,0.658,0.659,0.660,0.661,0.662,0.663,0.664,0.665,0.666,0.667
0,2,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,4,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9994,2,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
9995,3,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
9996,4,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
9997,5,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
9998,6,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

header parameter

In [ ]:
pd.read_csv("/content/sample_data/mnist_test.csv",header=1)

,2,0,0.1,0.2,0.3,0.4,0.5,0.6,0.7,0.8,...,0.609,0.610,0.611,0.612,0.613,0.614,0.615,0.616,0.617,0.618
0,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,4,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,4,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9993,2,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
9994,3,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
9995,4,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
9996,5,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
9997,6,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

use cols_parameter

In [ ]:
pd.read_csv('/content/sample_data/anscombe.json')

                                        [
  {"Series":"I"   "X":10.0 "Y":8.04}  NaN
                  "X":8.0  "Y":6.95}  NaN
                  "X":13.0 "Y":7.58}  NaN
                  "X":9.0  "Y":8.81}  NaN
                  "X":11.0 "Y":8.33}  NaN
                  "X":14.0 "Y":9.96}  NaN
                  "X":6.0  "Y":7.24}  NaN
                  "X":4.0  "Y":4.26}  NaN
                  "X":12.0 "Y":10.84} NaN
                  "X":7.0  "Y":4.81}  NaN
                  "X":5.0  "Y":5.68}  NaN
  {"Series":"II"  "X":10.0 "Y":9.14}  NaN
                  "X":8.0  "Y":8.14}  NaN
                  "X":13.0 "Y":8.74}  NaN
                  "X":9.0  "Y":8.77}  NaN
                  "X":11.0 "Y":9.26}  NaN
                  "X":14.0 "Y":8.10}  NaN
                  "X":6.0  "Y":6.13}  NaN
                  "X":4.0  "Y":3.10}  NaN
                  "X":12.0 "Y":9.13}  NaN
                  "X":7.0  "Y":7.26}  NaN
                  "X":5.0  "Y":4.74}  NaN
  {"Series":"III" "X":10.0 "Y":7.46}  NaN
                  "X":8.0  "Y":6.77}  NaN
                  "X":13.0 "Y":12.74} NaN
                  "X":9.0  "Y":7.11}  NaN
                  "X":11.0 "Y":7.81}  NaN
                  "X":14.0 "Y":8.84}  NaN
                  "X":6.0  "Y":6.08}  NaN
                  "X":4.0  "Y":5.39}  NaN
                  "X":12.0 "Y":8.15}  NaN
                  "X":7.0  "Y":6.42}  NaN
                  "X":5.0  "Y":5.73}  NaN
  {"Series":"IV"  "X":8.0  "Y":6.58}  NaN
                           "Y":5.76}  NaN
                           "Y":7.71}  NaN
                           "Y":8.84}  NaN
                           "Y":8.47}  NaN
                           "Y":7.04}  NaN
                           "Y":5.25}  NaN
                  "X":19.0 "Y":12.50} NaN
                  "X":8.0  "Y":5.56}  NaN
                           "Y":7.91}  NaN
                           "Y":6.89}  NaN
]                 NaN      NaN        NaN

In [ ]:
pd.read_csv('/content/sample_data/california_housing_train.csv',)

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value
0,-114.31,34.19,15.0,5612.0,1283.0,1015.0,472.0,1.4936,66900.0
1,-114.47,34.40,19.0,7650.0,1901.0,1129.0,463.0,1.8200,80100.0
2,-114.56,33.69,17.0,720.0,174.0,333.0,117.0,1.6509,85700.0
3,-114.57,33.64,14.0,1501.0,337.0,515.0,226.0,3.1917,73400.0
4,-114.57,33.57,20.0,1454.0,326.0,624.0,262.0,1.9250,65500.0
...,...,...,...,...,...,...,...,...,...
16995,-124.26,40.58,52.0,2217.0,394.0,907.0,369.0,2.3571,111400.0
16996,-124.27,40.69,36.0,2349.0,528.0,1194.0,465.0,2.5179,79000.0
16997,-124.30,41.84,17.0,2677.0,531.0,1244.0,456.0,3.0313,103600.0
16998,-124.30,41.80,19.0,2672.0,552.0,1298.0,478.0,1.9797,85800.0
16999,-124.35,40.54,52.0,1820.0,300.0,806.0,270.0,3.0147,94600.0

skiprows/nrows parameter

In [ ]:
pd.read_csv('/content/sample_data/california_housing_train.csv', skiprows=[0,2])

,-114.310000,34.190000,15.000000,5612.000000,1283.000000,1015.000000,472.000000,1.493600,66900.000000
0,-114.56,33.69,17.0,720.0,174.0,333.0,117.0,1.6509,85700.0
1,-114.57,33.64,14.0,1501.0,337.0,515.0,226.0,3.1917,73400.0
2,-114.57,33.57,20.0,1454.0,326.0,624.0,262.0,1.9250,65500.0
3,-114.58,33.63,29.0,1387.0,236.0,671.0,239.0,3.3438,74000.0
4,-114.58,33.61,25.0,2907.0,680.0,1841.0,633.0,2.6768,82400.0
...,...,...,...,...,...,...,...,...,...
16993,-124.26,40.58,52.0,2217.0,394.0,907.0,369.0,2.3571,111400.0
16994,-124.27,40.69,36.0,2349.0,528.0,1194.0,465.0,2.5179,79000.0
16995,-124.30,41.84,17.0,2677.0,531.0,1244.0,456.0,3.0313,103600.0
16996,-124.30,41.80,19.0,2672.0,552.0,1298.0,478.0,1.9797,85800.0
16997,-124.35,40.54,52.0,1820.0,300.0,806.0,270.0,3.0147,94600.0

In [ ]:
pd.read_csv('/content/sample_data/california_housing_train.csv', nrows=100)

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value
0,-114.31,34.19,15.0,5612.0,1283.0,1015.0,472.0,1.4936,66900.0
1,-114.47,34.40,19.0,7650.0,1901.0,1129.0,463.0,1.8200,80100.0
2,-114.56,33.69,17.0,720.0,174.0,333.0,117.0,1.6509,85700.0
3,-114.57,33.64,14.0,1501.0,337.0,515.0,226.0,3.1917,73400.0
4,-114.57,33.57,20.0,1454.0,326.0,624.0,262.0,1.9250,65500.0
...,...,...,...,...,...,...,...,...,...
95,-115.58,32.81,5.0,805.0,143.0,458.0,143.0,4.4750,96300.0
96,-115.58,32.81,10.0,1088.0,203.0,533.0,201.0,3.6597,87500.0
97,-115.58,32.79,14.0,1687.0,507.0,762.0,451.0,1.6635,64400.0
98,-115.58,32.78,5.0,2494.0,414.0,1416.0,421.0,5.7843,110100.0
99,-115.59,32.85,20.0,1608.0,274.0,862.0,248.0,4.8750,90800.0

encoding parameter

In [ ]:
pd.read_csv('/content/sample_data/california_housing_train.csv',encoding='latin-1')

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value
0,-114.31,34.19,15.0,5612.0,1283.0,1015.0,472.0,1.4936,66900.0
1,-114.47,34.40,19.0,7650.0,1901.0,1129.0,463.0,1.8200,80100.0
2,-114.56,33.69,17.0,720.0,174.0,333.0,117.0,1.6509,85700.0
3,-114.57,33.64,14.0,1501.0,337.0,515.0,226.0,3.1917,73400.0
4,-114.57,33.57,20.0,1454.0,326.0,624.0,262.0,1.9250,65500.0
...,...,...,...,...,...,...,...,...,...
16995,-124.26,40.58,52.0,2217.0,394.0,907.0,369.0,2.3571,111400.0
16996,-124.27,40.69,36.0,2349.0,528.0,1194.0,465.0,2.5179,79000.0
16997,-124.30,41.84,17.0,2677.0,531.0,1244.0,456.0,3.0313,103600.0
16998,-124.30,41.80,19.0,2672.0,552.0,1298.0,478.0,1.9797,85800.0
16999,-124.35,40.54,52.0,1820.0,300.0,806.0,270.0,3.0147,94600.0

skip bad lines

In [ ]:
pd.read_csv('/content/sample_data/california_housing_train.csv',sep=',', encoding='latin-1',on_bad_lines='skip')

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value
0,-114.31,34.19,15.0,5612.0,1283.0,1015.0,472.0,1.4936,66900.0
1,-114.47,34.40,19.0,7650.0,1901.0,1129.0,463.0,1.8200,80100.0
2,-114.56,33.69,17.0,720.0,174.0,333.0,117.0,1.6509,85700.0
3,-114.57,33.64,14.0,1501.0,337.0,515.0,226.0,3.1917,73400.0
4,-114.57,33.57,20.0,1454.0,326.0,624.0,262.0,1.9250,65500.0
...,...,...,...,...,...,...,...,...,...
16995,-124.26,40.58,52.0,2217.0,394.0,907.0,369.0,2.3571,111400.0
16996,-124.27,40.69,36.0,2349.0,528.0,1194.0,465.0,2.5179,79000.0
16997,-124.30,41.84,17.0,2677.0,531.0,1244.0,456.0,3.0313,103600.0
16998,-124.30,41.80,19.0,2672.0,552.0,1298.0,478.0,1.9797,85800.0
16999,-124.35,40.54,52.0,1820.0,300.0,806.0,270.0,3.0147,94600.0

dtypes parameter

In [ ]:
pd.read_csv('/content/sample_data/california_housing_train.csv', dtype={'median_house_value': int}).info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 17000 entries, 0 to 16999
Data columns (total 9 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   longitude           17000 non-null  float64
 1   latitude            17000 non-null  float64
 2   housing_median_age  17000 non-null  float64
 3   total_rooms         17000 non-null  float64
 4   total_bedrooms      17000 non-null  float64
 5   population          17000 non-null  float64
 6   households          17000 non-null  float64
 7   median_income       17000 non-null  float64
 8   median_house_value  17000 non-null  int64
dtypes: float64(8), int64(1)
memory usage: 1.2 MB

handling dates

converter

In [ ]:
def rename(name):
  if name == 'royal chalenger banglore':
    return 'rcb'

  else:
    return name

In [ ]:
rename('royal chanlenger banglore')

'royal chanlenger banglore'

loading a hug dataset in chunks

In [ ]:
dfs = pd.read_csv('/content/sample_data/california_housing_train.csv',chunksize=500)

In [ ]:
for chunks in dfs:
  print(chunks.shape)

(500, 9)
(500, 9)
(500, 9)
(500, 9)
(500, 9)
(500, 9)
(500, 9)
(500, 9)
(500, 9)
(500, 9)
(500, 9)
(500, 9)
(500, 9)
(500, 9)
(500, 9)
(500, 9)
(500, 9)
(500, 9)
(500, 9)
(500, 9)
(500, 9)
(500, 9)
(500, 9)
(500, 9)
(500, 9)
(500, 9)
(500, 9)
(500, 9)
(500, 9)
(500, 9)
(500, 9)
(500, 9)
(500, 9)
(500, 9)